spring:
  application:
    name: pagamentos-ms
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/alurafood-pagamento?createDatabaseIfNotExist=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  jpa:
    show-sql: true
  flyway:
    enabled: true
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
gateway:
  secret: ${GATEWAY_SECRET:minha-chave-secreta-gateway-2025}
resilience4j:
  circuitbreaker:
    instances:
      atualizaPedido:
        slidingWindowSize: 3
        minimumNumberOfCalls: 2
        waitDurationInOpenState: 50s
